# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import operator_pb2 as operator__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in operator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OperatorServiceStub(object):
    """Breaking migration: the previous full-state run APIs are replaced by bounded
    summary, snapshot, detail, and typed update APIs below. Remote operators and
    clients must upgrade together.

    ── Service ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCatalog = channel.unary_unary(
                '/avalanche.operator.OperatorService/GetCatalog',
                request_serializer=operator__pb2.Empty.SerializeToString,
                response_deserializer=operator__pb2.CatalogSnapshotMsg.FromString,
                _registered_method=True)
        self.StartRun = channel.unary_unary(
                '/avalanche.operator.OperatorService/StartRun',
                request_serializer=operator__pb2.StartRunRequest.SerializeToString,
                response_deserializer=operator__pb2.StartRunResponse.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/avalanche.operator.OperatorService/CancelRun',
                request_serializer=operator__pb2.CancelRunRequest.SerializeToString,
                response_deserializer=operator__pb2.Empty.FromString,
                _registered_method=True)
        self.GetRunResult = channel.unary_unary(
                '/avalanche.operator.OperatorService/GetRunResult',
                request_serializer=operator__pb2.GetRunRequest.SerializeToString,
                response_deserializer=operator__pb2.RunResultMsg.FromString,
                _registered_method=True)
        self.ListRunSummaries = channel.unary_unary(
                '/avalanche.operator.OperatorService/ListRunSummaries',
                request_serializer=operator__pb2.ListRunSummariesRequest.SerializeToString,
                response_deserializer=operator__pb2.RunSummaryPage.FromString,
                _registered_method=True)
        self.GetRunSnapshot = channel.unary_unary(
                '/avalanche.operator.OperatorService/GetRunSnapshot',
                request_serializer=operator__pb2.GetRunSnapshotRequest.SerializeToString,
                response_deserializer=operator__pb2.RunSnapshotMsg.FromString,
                _registered_method=True)
        self.GetLatestRunSnapshot = channel.unary_unary(
                '/avalanche.operator.OperatorService/GetLatestRunSnapshot',
                request_serializer=operator__pb2.GetLatestRunSnapshotRequest.SerializeToString,
                response_deserializer=operator__pb2.RunSnapshotMsg.FromString,
                _registered_method=True)
        self.ListLogs = channel.unary_unary(
                '/avalanche.operator.OperatorService/ListLogs',
                request_serializer=operator__pb2.ListLogsRequest.SerializeToString,
                response_deserializer=operator__pb2.LogPage.FromString,
                _registered_method=True)
        self.ListAgentEvents = channel.unary_unary(
                '/avalanche.operator.OperatorService/ListAgentEvents',
                request_serializer=operator__pb2.ListAgentEventsRequest.SerializeToString,
                response_deserializer=operator__pb2.AgentEventPage.FromString,
                _registered_method=True)
        self.ReadTrace = channel.unary_stream(
                '/avalanche.operator.OperatorService/ReadTrace',
                request_serializer=operator__pb2.ReadTraceRequest.SerializeToString,
                response_deserializer=operator__pb2.TraceChunk.FromString,
                _registered_method=True)
        self.ReadDetail = channel.unary_stream(
                '/avalanche.operator.OperatorService/ReadDetail',
                request_serializer=operator__pb2.ReadDetailRequest.SerializeToString,
                response_deserializer=operator__pb2.DetailChunk.FromString,
                _registered_method=True)
        self.StreamOperatorUpdates = channel.unary_stream(
                '/avalanche.operator.OperatorService/StreamOperatorUpdates',
                request_serializer=operator__pb2.StreamOperatorUpdatesRequest.SerializeToString,
                response_deserializer=operator__pb2.OperatorUpdateEnvelope.FromString,
                _registered_method=True)


class OperatorServiceServicer(object):
    """Breaking migration: the previous full-state run APIs are replaced by bounded
    summary, snapshot, detail, and typed update APIs below. Remote operators and
    clients must upgrade together.

    ── Service ─────────────────────────────────────────────

    """

    def GetCatalog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunSummaries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestRunSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgentEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadTrace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamOperatorUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCatalog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCatalog,
                    request_deserializer=operator__pb2.Empty.FromString,
                    response_serializer=operator__pb2.CatalogSnapshotMsg.SerializeToString,
            ),
            'StartRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRun,
                    request_deserializer=operator__pb2.StartRunRequest.FromString,
                    response_serializer=operator__pb2.StartRunResponse.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=operator__pb2.CancelRunRequest.FromString,
                    response_serializer=operator__pb2.Empty.SerializeToString,
            ),
            'GetRunResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunResult,
                    request_deserializer=operator__pb2.GetRunRequest.FromString,
                    response_serializer=operator__pb2.RunResultMsg.SerializeToString,
            ),
            'ListRunSummaries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunSummaries,
                    request_deserializer=operator__pb2.ListRunSummariesRequest.FromString,
                    response_serializer=operator__pb2.RunSummaryPage.SerializeToString,
            ),
            'GetRunSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunSnapshot,
                    request_deserializer=operator__pb2.GetRunSnapshotRequest.FromString,
                    response_serializer=operator__pb2.RunSnapshotMsg.SerializeToString,
            ),
            'GetLatestRunSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestRunSnapshot,
                    request_deserializer=operator__pb2.GetLatestRunSnapshotRequest.FromString,
                    response_serializer=operator__pb2.RunSnapshotMsg.SerializeToString,
            ),
            'ListLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLogs,
                    request_deserializer=operator__pb2.ListLogsRequest.FromString,
                    response_serializer=operator__pb2.LogPage.SerializeToString,
            ),
            'ListAgentEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgentEvents,
                    request_deserializer=operator__pb2.ListAgentEventsRequest.FromString,
                    response_serializer=operator__pb2.AgentEventPage.SerializeToString,
            ),
            'ReadTrace': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadTrace,
                    request_deserializer=operator__pb2.ReadTraceRequest.FromString,
                    response_serializer=operator__pb2.TraceChunk.SerializeToString,
            ),
            'ReadDetail': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadDetail,
                    request_deserializer=operator__pb2.ReadDetailRequest.FromString,
                    response_serializer=operator__pb2.DetailChunk.SerializeToString,
            ),
            'StreamOperatorUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamOperatorUpdates,
                    request_deserializer=operator__pb2.StreamOperatorUpdatesRequest.FromString,
                    response_serializer=operator__pb2.OperatorUpdateEnvelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'avalanche.operator.OperatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('avalanche.operator.OperatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OperatorService(object):
    """Breaking migration: the previous full-state run APIs are replaced by bounded
    summary, snapshot, detail, and typed update APIs below. Remote operators and
    clients must upgrade together.

    ── Service ─────────────────────────────────────────────

    """

    @staticmethod
    def GetCatalog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorService/GetCatalog',
            operator__pb2.Empty.SerializeToString,
            operator__pb2.CatalogSnapshotMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorService/StartRun',
            operator__pb2.StartRunRequest.SerializeToString,
            operator__pb2.StartRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorService/CancelRun',
            operator__pb2.CancelRunRequest.SerializeToString,
            operator__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorService/GetRunResult',
            operator__pb2.GetRunRequest.SerializeToString,
            operator__pb2.RunResultMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunSummaries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorService/ListRunSummaries',
            operator__pb2.ListRunSummariesRequest.SerializeToString,
            operator__pb2.RunSummaryPage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorService/GetRunSnapshot',
            operator__pb2.GetRunSnapshotRequest.SerializeToString,
            operator__pb2.RunSnapshotMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestRunSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorService/GetLatestRunSnapshot',
            operator__pb2.GetLatestRunSnapshotRequest.SerializeToString,
            operator__pb2.RunSnapshotMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorService/ListLogs',
            operator__pb2.ListLogsRequest.SerializeToString,
            operator__pb2.LogPage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgentEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorService/ListAgentEvents',
            operator__pb2.ListAgentEventsRequest.SerializeToString,
            operator__pb2.AgentEventPage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/avalanche.operator.OperatorService/ReadTrace',
            operator__pb2.ReadTraceRequest.SerializeToString,
            operator__pb2.TraceChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/avalanche.operator.OperatorService/ReadDetail',
            operator__pb2.ReadDetailRequest.SerializeToString,
            operator__pb2.DetailChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamOperatorUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/avalanche.operator.OperatorService/StreamOperatorUpdates',
            operator__pb2.StreamOperatorUpdatesRequest.SerializeToString,
            operator__pb2.OperatorUpdateEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OperatorServiceV2Stub(object):
    """V2 is additive: legacy clients remain on OperatorService until they complete
    their own migration. V2 requests derive their authorization scope from
    transport metadata and use only V2 request and response messages.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DiscoverFlows = channel.unary_unary(
                '/avalanche.operator.OperatorServiceV2/DiscoverFlows',
                request_serializer=operator__pb2.DiscoverFlowsRequestV2.SerializeToString,
                response_deserializer=operator__pb2.FlowListV2.FromString,
                _registered_method=True)
        self.StartRun = channel.unary_unary(
                '/avalanche.operator.OperatorServiceV2/StartRun',
                request_serializer=operator__pb2.StartRunRequestV2.SerializeToString,
                response_deserializer=operator__pb2.StartRunResponseV2.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/avalanche.operator.OperatorServiceV2/CancelRun',
                request_serializer=operator__pb2.CancelRunRequestV2.SerializeToString,
                response_deserializer=operator__pb2.CancelRunResponseV2.FromString,
                _registered_method=True)
        self.ListRunSummaries = channel.unary_unary(
                '/avalanche.operator.OperatorServiceV2/ListRunSummaries',
                request_serializer=operator__pb2.ListRunSummariesRequestV2.SerializeToString,
                response_deserializer=operator__pb2.RunSummaryPageV2.FromString,
                _registered_method=True)
        self.GetRunSnapshot = channel.unary_unary(
                '/avalanche.operator.OperatorServiceV2/GetRunSnapshot',
                request_serializer=operator__pb2.GetRunSnapshotRequestV2.SerializeToString,
                response_deserializer=operator__pb2.RunSnapshotV2.FromString,
                _registered_method=True)
        self.ListRunActivity = channel.unary_unary(
                '/avalanche.operator.OperatorServiceV2/ListRunActivity',
                request_serializer=operator__pb2.ListRunActivityRequestV2.SerializeToString,
                response_deserializer=operator__pb2.RunActivityPageV2.FromString,
                _registered_method=True)
        self.ReadActivityDetail = channel.unary_stream(
                '/avalanche.operator.OperatorServiceV2/ReadActivityDetail',
                request_serializer=operator__pb2.ReadActivityDetailRequestV2.SerializeToString,
                response_deserializer=operator__pb2.ActivityDetailChunkV2.FromString,
                _registered_method=True)
        self.GetRunResult = channel.unary_unary(
                '/avalanche.operator.OperatorServiceV2/GetRunResult',
                request_serializer=operator__pb2.GetRunResultRequestV2.SerializeToString,
                response_deserializer=operator__pb2.RunResultV2.FromString,
                _registered_method=True)
        self.ListRunOutputArtifacts = channel.unary_unary(
                '/avalanche.operator.OperatorServiceV2/ListRunOutputArtifacts',
                request_serializer=operator__pb2.ListRunOutputArtifactsRequestV2.SerializeToString,
                response_deserializer=operator__pb2.RunOutputArtifactPageV2.FromString,
                _registered_method=True)
        self.ReadRunOutputArtifact = channel.unary_stream(
                '/avalanche.operator.OperatorServiceV2/ReadRunOutputArtifact',
                request_serializer=operator__pb2.ReadRunOutputArtifactRequestV2.SerializeToString,
                response_deserializer=operator__pb2.RunOutputArtifactChunkV2.FromString,
                _registered_method=True)
        self.WatchRunStatus = channel.unary_stream(
                '/avalanche.operator.OperatorServiceV2/WatchRunStatus',
                request_serializer=operator__pb2.WatchRunStatusRequestV2.SerializeToString,
                response_deserializer=operator__pb2.RunStatusEnvelopeV2.FromString,
                _registered_method=True)


class OperatorServiceV2Servicer(object):
    """V2 is additive: legacy clients remain on OperatorService until they complete
    their own migration. V2 requests derive their authorization scope from
    transport metadata and use only V2 request and response messages.
    """

    def DiscoverFlows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunSummaries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunActivity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadActivityDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunOutputArtifacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRunOutputArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchRunStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperatorServiceV2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DiscoverFlows': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverFlows,
                    request_deserializer=operator__pb2.DiscoverFlowsRequestV2.FromString,
                    response_serializer=operator__pb2.FlowListV2.SerializeToString,
            ),
            'StartRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRun,
                    request_deserializer=operator__pb2.StartRunRequestV2.FromString,
                    response_serializer=operator__pb2.StartRunResponseV2.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=operator__pb2.CancelRunRequestV2.FromString,
                    response_serializer=operator__pb2.CancelRunResponseV2.SerializeToString,
            ),
            'ListRunSummaries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunSummaries,
                    request_deserializer=operator__pb2.ListRunSummariesRequestV2.FromString,
                    response_serializer=operator__pb2.RunSummaryPageV2.SerializeToString,
            ),
            'GetRunSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunSnapshot,
                    request_deserializer=operator__pb2.GetRunSnapshotRequestV2.FromString,
                    response_serializer=operator__pb2.RunSnapshotV2.SerializeToString,
            ),
            'ListRunActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunActivity,
                    request_deserializer=operator__pb2.ListRunActivityRequestV2.FromString,
                    response_serializer=operator__pb2.RunActivityPageV2.SerializeToString,
            ),
            'ReadActivityDetail': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadActivityDetail,
                    request_deserializer=operator__pb2.ReadActivityDetailRequestV2.FromString,
                    response_serializer=operator__pb2.ActivityDetailChunkV2.SerializeToString,
            ),
            'GetRunResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunResult,
                    request_deserializer=operator__pb2.GetRunResultRequestV2.FromString,
                    response_serializer=operator__pb2.RunResultV2.SerializeToString,
            ),
            'ListRunOutputArtifacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunOutputArtifacts,
                    request_deserializer=operator__pb2.ListRunOutputArtifactsRequestV2.FromString,
                    response_serializer=operator__pb2.RunOutputArtifactPageV2.SerializeToString,
            ),
            'ReadRunOutputArtifact': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadRunOutputArtifact,
                    request_deserializer=operator__pb2.ReadRunOutputArtifactRequestV2.FromString,
                    response_serializer=operator__pb2.RunOutputArtifactChunkV2.SerializeToString,
            ),
            'WatchRunStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchRunStatus,
                    request_deserializer=operator__pb2.WatchRunStatusRequestV2.FromString,
                    response_serializer=operator__pb2.RunStatusEnvelopeV2.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'avalanche.operator.OperatorServiceV2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('avalanche.operator.OperatorServiceV2', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OperatorServiceV2(object):
    """V2 is additive: legacy clients remain on OperatorService until they complete
    their own migration. V2 requests derive their authorization scope from
    transport metadata and use only V2 request and response messages.
    """

    @staticmethod
    def DiscoverFlows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorServiceV2/DiscoverFlows',
            operator__pb2.DiscoverFlowsRequestV2.SerializeToString,
            operator__pb2.FlowListV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorServiceV2/StartRun',
            operator__pb2.StartRunRequestV2.SerializeToString,
            operator__pb2.StartRunResponseV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorServiceV2/CancelRun',
            operator__pb2.CancelRunRequestV2.SerializeToString,
            operator__pb2.CancelRunResponseV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunSummaries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorServiceV2/ListRunSummaries',
            operator__pb2.ListRunSummariesRequestV2.SerializeToString,
            operator__pb2.RunSummaryPageV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorServiceV2/GetRunSnapshot',
            operator__pb2.GetRunSnapshotRequestV2.SerializeToString,
            operator__pb2.RunSnapshotV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorServiceV2/ListRunActivity',
            operator__pb2.ListRunActivityRequestV2.SerializeToString,
            operator__pb2.RunActivityPageV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadActivityDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/avalanche.operator.OperatorServiceV2/ReadActivityDetail',
            operator__pb2.ReadActivityDetailRequestV2.SerializeToString,
            operator__pb2.ActivityDetailChunkV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorServiceV2/GetRunResult',
            operator__pb2.GetRunResultRequestV2.SerializeToString,
            operator__pb2.RunResultV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunOutputArtifacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorServiceV2/ListRunOutputArtifacts',
            operator__pb2.ListRunOutputArtifactsRequestV2.SerializeToString,
            operator__pb2.RunOutputArtifactPageV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadRunOutputArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/avalanche.operator.OperatorServiceV2/ReadRunOutputArtifact',
            operator__pb2.ReadRunOutputArtifactRequestV2.SerializeToString,
            operator__pb2.RunOutputArtifactChunkV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchRunStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/avalanche.operator.OperatorServiceV2/WatchRunStatus',
            operator__pb2.WatchRunStatusRequestV2.SerializeToString,
            operator__pb2.RunStatusEnvelopeV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
