# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import operator_pb2 as operator__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in operator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OperatorServiceStub(object):
    """Breaking migration: the previous full-state run APIs are replaced by bounded
    summary, snapshot, detail, and typed update APIs below. Remote operators and
    clients must upgrade together.

    ── Service ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListFlows = channel.unary_unary(
                '/avalanche.operator.OperatorService/ListFlows',
                request_serializer=operator__pb2.Empty.SerializeToString,
                response_deserializer=operator__pb2.FlowList.FromString,
                _registered_method=True)
        self.StartRun = channel.unary_unary(
                '/avalanche.operator.OperatorService/StartRun',
                request_serializer=operator__pb2.StartRunRequest.SerializeToString,
                response_deserializer=operator__pb2.StartRunResponse.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/avalanche.operator.OperatorService/CancelRun',
                request_serializer=operator__pb2.CancelRunRequest.SerializeToString,
                response_deserializer=operator__pb2.Empty.FromString,
                _registered_method=True)
        self.GetRunResult = channel.unary_unary(
                '/avalanche.operator.OperatorService/GetRunResult',
                request_serializer=operator__pb2.GetRunRequest.SerializeToString,
                response_deserializer=operator__pb2.RunResultMsg.FromString,
                _registered_method=True)
        self.ListRunSummaries = channel.unary_unary(
                '/avalanche.operator.OperatorService/ListRunSummaries',
                request_serializer=operator__pb2.ListRunSummariesRequest.SerializeToString,
                response_deserializer=operator__pb2.RunSummaryPage.FromString,
                _registered_method=True)
        self.GetRunSnapshot = channel.unary_unary(
                '/avalanche.operator.OperatorService/GetRunSnapshot',
                request_serializer=operator__pb2.GetRunSnapshotRequest.SerializeToString,
                response_deserializer=operator__pb2.RunSnapshotMsg.FromString,
                _registered_method=True)
        self.ListLogs = channel.unary_unary(
                '/avalanche.operator.OperatorService/ListLogs',
                request_serializer=operator__pb2.ListLogsRequest.SerializeToString,
                response_deserializer=operator__pb2.LogPage.FromString,
                _registered_method=True)
        self.ListAgentEvents = channel.unary_unary(
                '/avalanche.operator.OperatorService/ListAgentEvents',
                request_serializer=operator__pb2.ListAgentEventsRequest.SerializeToString,
                response_deserializer=operator__pb2.AgentEventPage.FromString,
                _registered_method=True)
        self.ReadTrace = channel.unary_stream(
                '/avalanche.operator.OperatorService/ReadTrace',
                request_serializer=operator__pb2.ReadTraceRequest.SerializeToString,
                response_deserializer=operator__pb2.TraceChunk.FromString,
                _registered_method=True)
        self.ReadDetail = channel.unary_stream(
                '/avalanche.operator.OperatorService/ReadDetail',
                request_serializer=operator__pb2.ReadDetailRequest.SerializeToString,
                response_deserializer=operator__pb2.DetailChunk.FromString,
                _registered_method=True)
        self.StreamRunUpdates = channel.unary_stream(
                '/avalanche.operator.OperatorService/StreamRunUpdates',
                request_serializer=operator__pb2.StreamRunUpdatesRequest.SerializeToString,
                response_deserializer=operator__pb2.RunUpdateEnvelope.FromString,
                _registered_method=True)


class OperatorServiceServicer(object):
    """Breaking migration: the previous full-state run APIs are replaced by bounded
    summary, snapshot, detail, and typed update APIs below. Remote operators and
    clients must upgrade together.

    ── Service ─────────────────────────────────────────────

    """

    def ListFlows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunSummaries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgentEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadTrace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRunUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListFlows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFlows,
                    request_deserializer=operator__pb2.Empty.FromString,
                    response_serializer=operator__pb2.FlowList.SerializeToString,
            ),
            'StartRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRun,
                    request_deserializer=operator__pb2.StartRunRequest.FromString,
                    response_serializer=operator__pb2.StartRunResponse.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=operator__pb2.CancelRunRequest.FromString,
                    response_serializer=operator__pb2.Empty.SerializeToString,
            ),
            'GetRunResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunResult,
                    request_deserializer=operator__pb2.GetRunRequest.FromString,
                    response_serializer=operator__pb2.RunResultMsg.SerializeToString,
            ),
            'ListRunSummaries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunSummaries,
                    request_deserializer=operator__pb2.ListRunSummariesRequest.FromString,
                    response_serializer=operator__pb2.RunSummaryPage.SerializeToString,
            ),
            'GetRunSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunSnapshot,
                    request_deserializer=operator__pb2.GetRunSnapshotRequest.FromString,
                    response_serializer=operator__pb2.RunSnapshotMsg.SerializeToString,
            ),
            'ListLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLogs,
                    request_deserializer=operator__pb2.ListLogsRequest.FromString,
                    response_serializer=operator__pb2.LogPage.SerializeToString,
            ),
            'ListAgentEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgentEvents,
                    request_deserializer=operator__pb2.ListAgentEventsRequest.FromString,
                    response_serializer=operator__pb2.AgentEventPage.SerializeToString,
            ),
            'ReadTrace': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadTrace,
                    request_deserializer=operator__pb2.ReadTraceRequest.FromString,
                    response_serializer=operator__pb2.TraceChunk.SerializeToString,
            ),
            'ReadDetail': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadDetail,
                    request_deserializer=operator__pb2.ReadDetailRequest.FromString,
                    response_serializer=operator__pb2.DetailChunk.SerializeToString,
            ),
            'StreamRunUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRunUpdates,
                    request_deserializer=operator__pb2.StreamRunUpdatesRequest.FromString,
                    response_serializer=operator__pb2.RunUpdateEnvelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'avalanche.operator.OperatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('avalanche.operator.OperatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OperatorService(object):
    """Breaking migration: the previous full-state run APIs are replaced by bounded
    summary, snapshot, detail, and typed update APIs below. Remote operators and
    clients must upgrade together.

    ── Service ─────────────────────────────────────────────

    """

    @staticmethod
    def ListFlows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorService/ListFlows',
            operator__pb2.Empty.SerializeToString,
            operator__pb2.FlowList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorService/StartRun',
            operator__pb2.StartRunRequest.SerializeToString,
            operator__pb2.StartRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorService/CancelRun',
            operator__pb2.CancelRunRequest.SerializeToString,
            operator__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorService/GetRunResult',
            operator__pb2.GetRunRequest.SerializeToString,
            operator__pb2.RunResultMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunSummaries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorService/ListRunSummaries',
            operator__pb2.ListRunSummariesRequest.SerializeToString,
            operator__pb2.RunSummaryPage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorService/GetRunSnapshot',
            operator__pb2.GetRunSnapshotRequest.SerializeToString,
            operator__pb2.RunSnapshotMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorService/ListLogs',
            operator__pb2.ListLogsRequest.SerializeToString,
            operator__pb2.LogPage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgentEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avalanche.operator.OperatorService/ListAgentEvents',
            operator__pb2.ListAgentEventsRequest.SerializeToString,
            operator__pb2.AgentEventPage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/avalanche.operator.OperatorService/ReadTrace',
            operator__pb2.ReadTraceRequest.SerializeToString,
            operator__pb2.TraceChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/avalanche.operator.OperatorService/ReadDetail',
            operator__pb2.ReadDetailRequest.SerializeToString,
            operator__pb2.DetailChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRunUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/avalanche.operator.OperatorService/StreamRunUpdates',
            operator__pb2.StreamRunUpdatesRequest.SerializeToString,
            operator__pb2.RunUpdateEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
